### PR TITLE
color should be same as bg of PARENT

### PR DESCRIPTION
**Pull request by wrex**
Fixes Issue #37 
(use --ED-surface-4 for text color)

### CODE REVIEW

**Review by Sepitus-exe — CHANGES_REQUESTED** [review]
Altering `.lessons-and-reviews__lessons-button span` is going to change the look of the span not only when the L/R queue is empty, but even when it's populated.

I would suggest moving the changes to their own new style under the `.lessons-and-reviews__lessons-button--0 span` selector which will affect the span only when the queue is empty.

**Comment by wrex** [comment]
About to board. Will take care of this tomorrow.

**Review by Sepitus-exe — APPROVED** [review]
Having the --0 class change only the variables is very clever, I like it.

**Comment by wrex** [comment]
Yeah, it's a useful trick. CSS before custom properties was a pain!

**Pull request merged**
