### PR TITLE
semantically named derived colors, theme ultimate timeline

### PR DESCRIPTION
**Pull request by wrex**
This adds basic theming for the Ultimate Timeline userscript.

It also creates some semantically named derived colors for you to use at the top. This should make things more readable/understandable throughout.

Lastly, note that the Ultimate timeline also creates some custom props for colors. This makes things really easy to tinker with consistently.

### CODE REVIEW

**Comment by wrex** [comment]
Here's an example of what the timeline looks like themed.
Screenshot 2023-01-14 at 10 39 56 AM

**Comment by Sepitus-exe** [comment]
Looks like we have been chipping on the same thing. I just pushed out styling for the ultimate timeline

UltimateTimeline1
UltimateTimeline2

**Comment by Sepitus-exe** [comment]
But I will definetly check out your solution as it seems more compact as well as take a look at the updated color solution

**Comment by wrex** [comment]
No worries! Use whatever makes the most sense to you.

Please do take a look at how I redefined the custom-props in my version. I think you'll quickly grok why props based on props make things easier to maintain (while remaining consistent). That pattern is showing up everywhere these days.

**Pull request closed without merging**
