### PR TITLE
45-47 style search & user synonyms

### PR DESCRIPTION
**Pull request by Sepitus-exe**
Trivial changes to fix the issues #45, #46 and #47
image
image

### CODE REVIEW

**Comment by wrex** [comment]
Just a note that '&' in a branch name has to be escaped for git commands. Probably best to avoid.

**Comment by wrex** [comment]
I think the search fixes are fine, but I'll wait to merge until I'm home on a bigger screen.

I think this undoes the 36 color changes if I merge it without edits.

**Comment by wrex** [comment]
I've merged all your pull requests (all looked fine).

Unfortunately, I think I merged them in the wrong order, causing the merges to undo some of the fixes. I'll try to figure this out and clean it up when I'm home and on a bigger screen.

**Comment by Sepitus-exe** [comment]
I took a look at it, and it seems all the changes were applied correctly. Git used some sort of black magic to figure out what was the essence of each PR and altered only the relevant parts of the css file.

**Pull request merged**
