### PR TITLE
Lesson notes background

### PR DESCRIPTION
**Pull request by Sepitus-exe**
image

### CODE REVIEW

**Comment by wrex** [comment]
Hmm. Not working for me.

lesson-notes

Ah! You had a typo. The ID is `#lessons` (plurara), you had `#lesson`.

Also, I think in general that targeting and redefining Tailwind utility classes is a tricky business. 

In this case, I think a better selector might be:

```css
#lessons .font-lessons textarea {
  background-color: var(--ED-surface-3);
}
```

Target any `textarea` in `.font-lessons` rather than overriding a utility class that might be used elsewhere.

**Review by wrex — CHANGES_REQUESTED** [review]
You've a typo in the ID: Should be `#lessons` (plural).

Also, please consider changing the selector to `#lessons .note-lessons textarea` to be explicit about what you're styling (rather than overriding a tailwind utility class).

**Comment by Sepitus-exe** [comment]
Weird, there should be a div with the lesson id within the hierarchy.
image
Anyway, for consistency's sake, Im going to change the id to 'lessons'.

> Also, please consider changing the selector to `#lessons .note-lessons textarea` to be explicit about what you're styling (rather than overriding a tailwind utility class).

I initially opted to change the exact class responsible for the color of the element. I don't think it would prove problematic in the future, but I see your concerns and will be adjusting the selectors appropriately.

**Review by wrex — APPROVED** [review]

**Comment by wrex** [comment]
> Weird, there should be a div with the lesson id within the hierarchy.

Huh. I'm not sure why that wasn't on my specific lesson. I'll be interested to see if the new selector covers all cases or not.

FIngers crossed.

**Pull request merged**
